### ISSUE TITLE
Getting error when trying to run server

### ISSUE THREAD

**Issue by jerrythimothyj** [farskid/cordova-react-redux-boilerplate#1]
> Cordova-react-redux-boilerplate@0.0.1 server D:\JERRY\CODES\cordova\6\cordova-
react-redux-boilerplate
> export NODE_ENV=development && webpack-dev-server --config webpack.config.js -
-inline --content-base www/ --port 3200

'export' is not recognized as an internal or external command,
operable program or batch file.

**Comment by farskid** [comment]
Hello @jerrythimothyj 
What operating system and which version of Cordova are you using?

**Comment by jerrythimothyj** [comment]
Windows 8.1 Pro and Cordova 6.5.0 @farskid .

**Comment by farskid** [comment]
@jerrythimothyj Let me check for the errors and get back to you.

**Comment by farskid** [comment]
@jerrythimothyj This is because `export` is only valid in unix platforms. use `SET` instead of `export` for windows. I'll update the readme for that.
I'm also going to mark this issue as closed. Feel free to share more if the issue still remains.
